param(
  [string]$Root = ".",
  [string]$Members = ""
)

$ErrorActionPreference = "Stop"

$rootPath = Resolve-Path -LiteralPath $Root
$docsProject = Join-Path $rootPath "docs/project"
$tasksRoot = Join-Path $rootPath "docs/tasks"

if (-not (Test-Path -LiteralPath $docsProject -PathType Container)) {
  throw "Missing docs/project. Run pipeline.ps1 onboard or init-project first."
}

if (-not (Test-Path -LiteralPath $tasksRoot -PathType Container)) {
  New-Item -ItemType Directory -Path $tasksRoot -Force | Out-Null
}

function Read-Text {
  param([string]$Path)
  if (Test-Path -LiteralPath $Path -PathType Leaf) {
    return Get-Content -Raw -LiteralPath $Path
  }
  return ""
}

function Get-FirstRegex {
  param(
    [string]$Text,
    [string]$Pattern
  )
  $match = [regex]::Match($Text, $Pattern, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
  if ($match.Success) {
    return $match.Groups[1].Value.Trim()
  }
  return ""
}

function Get-TaskInfo {
  param([System.IO.DirectoryInfo]$Folder)

  $scope = Read-Text (Join-Path $Folder.FullName "scope.md")
  $handoff = Read-Text (Join-Path $Folder.FullName "handoff.md")
  $review = Read-Text (Join-Path $Folder.FullName "review.md")

  $id = Get-FirstRegex $Folder.Name '^(TASK-\d{3,})'
  $name = $Folder.Name -replace '^TASK-\d{3,}-?', ''
  $status = Get-FirstRegex $scope '- Status:\s*(.+)'
  if ([string]::IsNullOrWhiteSpace($status)) { $status = "unknown" }
  $owner = Get-FirstRegex $scope '- Owner:\s*(.+)'
  if ([string]::IsNullOrWhiteSpace($owner)) { $owner = Get-FirstRegex $scope '- Respons[aá]vel:\s*(.+)' }
  if ([string]::IsNullOrWhiteSpace($owner)) { $owner = "unclaimed" }
  $branch = Get-FirstRegex $scope '- Branch:\s*(.+)'
  if ([string]::IsNullOrWhiteSpace($branch)) { $branch = Get-FirstRegex $scope '- Branch sugerida:\s*(.+)' }
  if ([string]::IsNullOrWhiteSpace($branch)) { $branch = "feat/$id-$name" }
  $dependencies = Get-FirstRegex $scope '(?s)## Dependencies\s+(.+?)(?:\r?\n##|\z)'
  if ([string]::IsNullOrWhiteSpace($dependencies)) { $dependencies = "None recorded." }

  $stage = "ready"
  if ($handoff -match 'Status:\s*not_started|Not implemented yet') {
    $stage = "ready"
  } elseif ($review -match 'Outcome:\s*pending|Review has not been performed') {
    $stage = "implemented_pending_review"
  } elseif ($review -match 'Outcome:\s*(approved|approved_with_notes)') {
    $stage = "reviewed"
  } elseif ($review -match 'Outcome:\s*rejected') {
    $stage = "rejected"
  }

  return [pscustomobject]@{
    Id = $id
    Name = $name
    Status = $status
    Owner = $owner
    Branch = $branch
    Stage = $stage
    Folder = "docs/tasks/$($Folder.Name)"
    Dependencies = (($dependencies -split "`r?`n" | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }) -join " ")
  }
}

$taskFolders = @()
if (Test-Path -LiteralPath $tasksRoot -PathType Container) {
  $taskFolders = @(Get-ChildItem -LiteralPath $tasksRoot -Directory | Where-Object { $_.Name -match '^TASK-\d{3,}-' } | Sort-Object Name)
}

$tasks = @($taskFolders | ForEach-Object { Get-TaskInfo $_ })
$memberList = @($Members -split ',' | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("# Team Plan")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("Generated by `.agents/scripts/plan_team.ps1`.")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("## Rules")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("- One task per branch.")
[void]$builder.AppendLine("- One task per PR.")
[void]$builder.AppendLine("- Claim a task before implementation.")
[void]$builder.AppendLine("- Avoid two people working on the same task unless the split is explicit.")
[void]$builder.AppendLine("- Treat `docs/project/` as protected shared memory.")
[void]$builder.AppendLine("")

if ($memberList.Count -gt 0) {
  [void]$builder.AppendLine("## Team Members")
  [void]$builder.AppendLine("")
  foreach ($member in $memberList) {
    [void]$builder.AppendLine("- $member")
  }
  [void]$builder.AppendLine("")
}

[void]$builder.AppendLine("## Work Map")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("| Task | Status | Stage | Owner | Branch | Folder | Dependencies |")
[void]$builder.AppendLine("| --- | --- | --- | --- | --- | --- | --- |")
if ($tasks.Count -eq 0) {
  [void]$builder.AppendLine("| none | - | - | - | - | - | - |")
} else {
  foreach ($task in $tasks) {
    $branchValue = $task.Branch
    $folderValue = $task.Folder
    $dependencyValue = $task.Dependencies.Replace('|','/')
    [void]$builder.AppendLine("| $($task.Id) $($task.Name) | $($task.Status) | $($task.Stage) | $($task.Owner) | ``$branchValue`` | ``$folderValue`` | $dependencyValue |")
  }
}

[void]$builder.AppendLine("")
[void]$builder.AppendLine("## Parallelization Notes")
[void]$builder.AppendLine("")
if ($tasks.Count -eq 0) {
  [void]$builder.AppendLine("- No tasks exist yet. Onboard the project and create backlog tasks from real current work.")
} else {
  $unclaimed = @($tasks | Where-Object { $_.Owner -eq "unclaimed" -and $_.Status -notmatch 'completed|cancelled' })
  $active = @($tasks | Where-Object { $_.Status -match 'active|in_review' })
  [void]$builder.AppendLine("- Unclaimed executable tasks: $($unclaimed.Count)")
  [void]$builder.AppendLine("- Active or in-review tasks: $($active.Count)")
  [void]$builder.AppendLine("- Review dependencies manually before assigning parallel work.")
}

$teamPlanPath = Join-Path $docsProject "team_plan.md"
Set-Content -LiteralPath $teamPlanPath -Value $builder.ToString() -Encoding UTF8

Write-Host "Team plan updated: docs/project/team_plan.md"
